# -*- coding: utf-8 -*-
# 網站內容資料。修改文字後執行：python3 _build/build.py

RESUME = "https://drive.google.com/file/d/1eXg35CQRQdaz5wshCMCsyUloGirA1fBz/view?usp=sharing"
EMAIL = "huangjiie0330@gmail.com"
LINKEDIN = "https://www.linkedin.com/in/harveyhuang30/"

CATEGORIES = [
    ("product", "產品設計", "Product Design"),
    ("visual", "視覺設計", "Visual Design"),
]

# gallery: list of image filenames, or ("text", 標題, 內文) blocks, or ("video", file) / ("youtube", id, caption)
# layout: "wide"(預設, 滿版單欄) | "tall"(長圖, 置中窄欄) | "grid3"(三欄)
PROJECTS = [
    {
        "slug": "jti-mini-app",
        "title": "JTI LINE Mini App",
        "zh": "JTI Ploom AURA 會員 LINE Mini App｜內部提案",
        "client": "JTI（Internal Pitch）",
        "cat": "product",
        "tags": ["LINE Mini App", "UX Research", "UX Strategy", "Interaction Design"],
        "role": ["UI Lead Design｜Harvey Huang"],
        "lead": "在喧囂之外，留一段只屬於自己的時刻。這是為 JTI 內部提案設計的 Ploom AURA 會員 LINE Mini App：從使用者訪談出發，將「安靜、放鬆」的使用情境，轉化為一套以氛圍與儀式感驅動的會員體驗，讓品牌不只被使用，而是陪伴成熟大人建立屬於自己的生活節奏。",
        "sections": [
            ("Insight", "訪談發現，使用者在使用產品的當下，追求的不是更多資訊，而是一段安靜、不被打擾的片刻。因此體驗設計的核心，從「功能效率」轉向「感受與節奏」。"),
            ("Concept", "以「新・大人禮儀」作為會員旅程的主軸，將車內、社交、Me Time 與居家四種生活情境，對應產品的四種色彩，讓每一次互動都成為一次得體、有品味的生活練習。"),
            ("Ambient Layer", "設計帶有聲光與煙霧質感的動態背景，以緩慢流動的光影營造療癒、沉浸的氛圍。介面退居其後，讓情緒先於資訊被感受。"),
            ("Ritual Journey", "以大人感的任務與內容取代傳統集點：每日情境提問、完成儀式、累積徽章，一步一步解鎖專屬權益，把會員經營從「交易」轉化為「養成」。"),
        ],
        "gallery": [
            ("video", "jti-mini-app.mp4"),
            "hero",
            ("text", "Ritual Journey｜一步一步，解鎖大人感", "從一個情境提問開始，使用者在完成儀式的過程中，重新思考自己與他人的相處方式；每完成一項任務，就離下一枚徽章更近一步，讓成長被看見，也讓品牌關係自然累積。"),
            "flow",
            ("text", "Interface｜讓介面安靜下來", "以深色基調、低彩度材質與柔和光暈建立沉穩的視覺語言，並透過卡片化的內容模組，讓禮儀內容、會員地圖、成人指數與徽章進度，在同一個節奏裡被瀏覽。"),
            "long",
        ],
    },
    {
        "slug": "psc-aio",
        "title": "JTI Store Staff System",
        "zh": "JTI 店員操作後台系統設計｜All in One",
        "client": "JTI",
        "cat": "product",
        "tags": ["Back Office", "UI Design", "Interaction Design"],
        "role": ["UI Lead Design｜Harvey Huang", "UX Lead Design｜Freddy Liu", "UX Research｜Freddy Liu, Harvey Huang"],
        "lead": "門市的每一次服務，都從店員手上的一台平板開始。All in One 是為 JTI 實體門市打造的店員操作後台：把登入、進店紀錄、結帳、會員、售後服務與服務體驗回饋整合進同一套介面。我負責 UI Lead，將複雜的門市作業轉化為一套沉穩、好上手、在忙碌現場也不容易出錯的操作體驗。",
        "sections": [
            ("Team", "UX 與 User Flow 由擔任 UX Lead 的 Freddy Liu 負責規劃；我擔任 UI Lead，負責視覺語言、介面架構落地、元件與互動狀態設計，並與開發團隊協作完成交付。"),
            ("Visual Language", "延續 Ploom 的品牌質感，以深色暖調與金色重點建立沉穩的操作環境；金色只用在當下聚焦的紀錄、分頁與選取狀態，讓店員在門市燈光下也能一眼看見重點。"),
            ("Layout", "左側固定導覽與問卷紀錄清單、右側以五個分頁承接進店紀錄、結帳、會員、售後服務與服務回饋。店員可以在多位顧客的紀錄之間快速切換，不必離開當前頁面。"),
            ("State Design", "所有分頁都設計「引導狀態」：尚未選擇進店目的時，內容以低彩度呈現並提示回到進店紀錄，避免漏填或跳步；完成前置步驟後才展開可操作的欄位。"),
        ],
        "gallery": [
            "hero",
            ("text", "Entry｜從登入開始建立信任", "登入頁以品牌氛圍影像襯底，降低系統感；首頁則清楚呈現登入身份、通路與服務店點、管理權限，以及今日與昨日來店人數，讓店長與店員一進系統就掌握現場狀況。"),
            "entry",
            ("text", "Core Modules｜五個分頁，一段完整的服務", "進店紀錄整合會員資格確認與年齡判別；結帳以勾選購買品項快速完成；會員頁支援保固裝置拍照上傳；售後服務則將障礙排除與換貨項目模組化，換貨清單可逐項新增、刪除。"),
            "modules",
            ("text", "State Design｜讓介面替店員記得下一步", "每個分頁都有未啟用與啟用兩種狀態。未完成進店紀錄時，欄位降低對比並給出「前往進店紀錄」的捷徑；完成後才展開填寫，讓流程順序自然被介面守住。"),
            "states",
            ("text", "Questionnaire｜把問卷變成好點的按鈕", "選購問卷以單選、複選標籤區分題型，選項做成大面積的觸控按鈕；門市服務體驗回饋則交給顧客填寫，以滿意度與 0–10 推薦分數收集回饋，送出後以完成畫面收尾。"),
            "survey",
            ("text", "Interaction｜拖曳卡片，快速整理紀錄", "問卷紀錄以卡片呈現顧客年齡與進店時間，長按拖曳至刪除區即可移除誤建的紀錄，減少在清單中層層點選的操作成本。"),
            "delete",
        ],
    },
    {
        "slug": "volkswagen-app",
        "title": "My Volkswagen App",
        "zh": "福斯汽車 My Volkswagen App 全新體驗",
        "client": "Volkswagen Taiwan",
        "cat": "product",
        "tags": ["App", "UX Research", "UI Design", "Design System"],
        "role": ["Project Owner｜Veronica Kuo, Winnie Lee", "UI Lead Design｜Harvey Huang", "UX Lead Design｜Freddy Liu", "UX Research｜Chialynn Wu, Freddy Liu, Harvey Huang", "Project Management｜Bryan Yu, Aoao Li", "Martech｜Eric Hsiao, Vic Lin, Eric Huang", "Vendor｜Cruisys", "Special Thanks｜Yvonne Wang"],
        "hero_video": ["volkswagen.mp4", "volkswagen-demo.mp4"],
        "hero_poster": ["film-poster", "demo-poster"],
        "featured": True,
        "lead": "My Volkswagen App 上線五年，卻因缺乏系統性的更新維運，出現主打功能使用率低、使用者體驗不佳與功能龐雜等問題。我們以車主為思考核心，重新打造一個真正符合車主需求的應用程式。",
        "award": "2024 DSA 數位奇點獎｜最佳顧客旅程介面設計商務行銷獎 金獎",
        "sections": [
            ("Challenge", "上線五年缺乏系統性更新：主打功能使用率低、使用者體驗不佳、功能龐雜，App 難以成為車主日常會打開的工具。"),
            ("Research", "透過競品分析、量化分析（Kano Model）與使用者訪談，深入了解車主的行為、痛點與期待，找出能加強與車主連結的機會。"),
            ("Strategy", "根據研究結果，找出三大優化方向：產品新定位、顧客旅程再設計、設計介面再優化。將 App 重新定位為「量身打造的專屬愛車秘書」，讓車主與愛車零距離。"),
            ("Outcome", "重新梳理售後服務與愛車資訊的架構，全面升級預約保養流程，共完成 200+ 頁介面設計，並獲得 2024 DSA 數位奇點獎金獎。"),
        ],
        "gallery": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "13"],
    },
    {
        "slug": "taipei-twins",
        "title": "Taipei Twins",
        "zh": "台北雙星 官方網站改版",
        "client": "台北雙星 TAIPEI TWINS",
        "cat": "product",
        "role": ["UI Lead Design｜Harvey Huang", "UX Design｜Freddy Liu, Harvey Huang"],
        "tags": ["Website", "UX Strategy", "UI Design", "RWD"],
        "featured": True,
        "lead": "2027 年台灣將有一座地標性新建築。隨著建築進展與國際招商啟動，舊官網的資訊架構混亂、瀏覽動線不佳、缺乏視覺調性等問題逐漸浮現。這次改版的目標，是讓新官網成為人們認識台北雙星的首要門面。",
        "sections": [
            ("Design Strategy", "以使用者為核心打造網站架構；以故事性互動導覽帶出全新網站視覺；並透過持續更新的內容，讓使用者隨時掌握開發進度。"),
            ("Execution", "01 主頁橫幅輪播放送品牌新定位　02 沉浸式動態導覽呈現設施概要　03 以使用者為核心的網站架構，精確分類好查找　04 AI 語言切換，打破語言隔閡　05 動態區塊，最新動向持續更新。"),
            ("Outcome", "新官網上線一個月，數據表現較去年同期成長 200% 以上。"),
        ],
        "gallery": [("video", "taipei-twins.mp4"), "1", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13"],
    },
    {
        "slug": "singleton-website",
        "title": "The Singleton",
        "zh": "帝亞吉歐 蘇格登 SINGLETON 品牌官網",
        "client": "Diageo",
        "cat": "product",
        "role": ["UI Lead Design｜Harvey Huang", "UX Lead Design｜Chiayu Hsu", "UX Research｜Freddy Liu, Harvey Huang"],
        "tags": ["Website", "Information Architecture", "UI Design"],
        "featured": True,
        "lead": "從 GA 數據出發重新檢視舊官網表現，重塑引導式體驗，讓品牌網站同時承擔品牌價值傳遞與商業導流的任務。",
        "sections": [
            ("Pain Point", "從舊官網數據發現，使用者在核心轉換頁面（如查詢銷售據點、報名活動 / 品酩會、加入社群等）的進入率極低。現有架構缺乏直觀的導引機制與明確的行動呼籲（CTA），導致流量在瀏覽過程中流失，未能轉化為商業行動。"),
            ("Task Analysis", "透過 Task Prioritization 理解使用者對此類品牌網站的關鍵需求，識別出哪些高價值任務因認知成本過高而造成高跳出率。以此為基準重新定義全站導流路徑，篩選出高頻互動的核心功能，重新梳理資訊架構（IA）與主要操作流程（Main Flow）。"),
            ("IA Restructure", "以五大重點功能為核心，建構對齊使用者認知的全站分類體系；提升關鍵入口能見度並佈局引導誘因，極小化操作摩擦力，優化使用者達成目標的關鍵路徑。"),
        ],
        "gallery": [
            ("text", "首頁｜善用首頁優勢，增加多元資訊模板", "舊版首頁資訊密度不足且缺乏導引機制，使用者難以建立品牌認知。我們將原本資訊稀疏的入口重塑為具感官沉浸感的探索起點，透過互動引導驅動探索動機，實現品牌價值傳遞與數據蒐集的雙重目標。"),
            "s4-1", "s4-2",
            ("text", "產品頁｜豐富化生活型態的內容", "透過情境式引導傳遞品牌價值；優化據點查詢動線，將產品探索轉化為具體的購買行動；並增加「飲藏酒單」區塊，由專家推薦延伸內容，建構完整的站內探索路徑。"),
            "s5",
        ],
    },
    {
        "slug": "shin-kong-mitsukoshi",
        "title": "Shin Kong Mitsukoshi",
        "zh": "新光三越 官方網站改版",
        "client": "新光三越 SHIN KONG MITSUKOSHI",
        "cat": "product",
        "role": ["UI Design｜Harvey Huang", "UX Lead Design｜Chiayu Hsu, Harvey Huang", "UX Intern｜Chialynn Wu"],
        "tags": ["Website", "UX Research", "Information Architecture", "UI Design"],
        "featured": True,
        "lead": "為百貨官網重新定義數位角色：從使用者研究出發，找出不同性格的消費者被吸引的資訊形式，重新規劃官網的設計策略與架構。",
        "sections": [
            ("Design Process", "以一連串的收斂與發散推進：Envision → Research → Insights & Ideation → Concept Design → Solution Prioritization → Detail Design & Iteration。"),
            ("User Research", "篩選不同類型的受訪者，包含無百貨通路消費習慣者、使用多個新光數位渠道的用戶、重度消費者與相關從業人員，深入了解他們使用數位工具的情境與期待。"),
            ("Insight & Strategy", "依用戶性格將消費者歸納為感覺派、務實派、跟隨型、主導型，發現不同性格的用戶容易被吸引的資訊形式也不盡相同，並據此訂定官網的設計策略與資訊架構。"),
        ],
        "gallery": ["2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
    },
    {
        "slug": "diageo-line-mini-app",
        "title": "Diageo LINE Mini App",
        "zh": "帝亞吉歐 會員 LINE Mini App",
        "client": "Diageo",
        "cat": "product",
        "role": ["UI Lead Design｜Harvey Huang", "UI Design｜Freddy Liu", "UX Lead Design｜Freddy Liu"],
        "tags": ["LINE Mini App", "Information Architecture", "UI Design", "Design System"],
        "featured": True,
        "lead": "為帝亞吉歐打造會員 LINE Mini App，重新整理會員服務的資訊架構，並建立統一的視覺風格指南。",
        "sections": [
            ("Information Architecture", "簡化導覽結構、降低操作層級；建立清晰的功能分區；並強化會員權益的可見性，讓會員快速找到需要的服務。"),
            ("UI Design", "系統性規劃並建立視覺風格指南，統一平台視覺語言與品牌呈現，確保整體設計的一致性與完整度，並據此完成 30+ 頁高保真介面設計。"),
        ],
        "gallery": ["2", "3", "4", ("join", "5", "6")],
    },
    {
        "slug": "diageo-liff-module",
        "title": "Receipt Registration & Modular System",
        "zh": "帝亞吉歐 發票登錄與模組化系統設計",
        "client": "Diageo",
        "cat": "product",
        "role": ["UI Design｜Harvey Huang"],
        "tags": ["LINE LIFF", "User Flow", "UI Design", "Design System"],
        "lead": "為品牌導入介面模組化與 Design Guideline 概念，透過標準化設計流程，讓品牌在不同傳播檔期中能敏捷更換活動網頁（Event Page）。",
        "sections": [
            ("Role", "全案統籌 UI 視覺、User Flow 流程規劃與設計指導，在確保數位互動創新與實用性的同時，進一步深化品牌與消費者間的數位聯結。"),
        ],
        "gallery": ["2", "3", "4"],
    },
    {
        "slug": "diageo-liff-page",
        "title": "The Singleton LINE LIFF Campaign",
        "zh": "帝亞吉歐 蘇格登「豐味旅城」LINE LIFF 活動頁",
        "client": "Diageo",
        "cat": "product",
        "role": ["UI Design｜Harvey Huang"],
        "tags": ["LINE LIFF", "Campaign", "User Flow", "UI Design"],
        "lead": "蘇格登 12 年「豐味旅城」LINE LIFF 活動頁，從主畫面、活動辦法、互動遊戲、中獎與抽獎紀錄，完整規劃活動的遊戲流程與介面。",
        "sections": [],
        "gallery": ["2", "3"],
    },
    {
        "slug": "tft-app",
        "title": "TFT App",
        "zh": "TFT 教師管理平台 App",
        "client": "TFT",
        "cat": "product",
        "role": ["UI Design｜Harvey Huang", "UX Lead Design｜Chiayu Hsu"],
        "tags": ["App", "Information Architecture", "User Flow", "Design System"],
        "lead": "以系統化的方式，協助教師達成班級指標管理。",
        "sections": [
            ("Target Users", "找出使用產品的四大族群：校長、班級導師、任科老師與家長，並釐清各自在班級管理中的需求與目標。"),
            ("Process", "從 Information Architecture、Flow Chart 到 Design System，逐步建立完整的產品架構與一致的介面規範。"),
        ],
        "gallery": ["1", "2", "3", "4", "5", "6", "7"],
    },
    {
        "slug": "samsung-dashboard",
        "title": "SAMSUNG Dashboard",
        "zh": "SAMSUNG 內部 Dashboard 介面設計",
        "client": "SAMSUNG（Internal）",
        "cat": "product",
        "role": ["UI Design｜Harvey Huang"],
        "tags": ["Dashboard", "Data Visualization", "UI Design"],
        "cover": "1",
        "lead": "企業內部使用的 Dashboard 介面設計，將大量數據與列表整理成清楚易讀的視覺層級。",
        "sections": [],
        "hero_video": "samsung-1.mp4",
        "hero_poster": "video-poster",
        "gallery": [("loop", "samsung-2.mp4"), ("loop", "samsung-3.mp4"), ("loop", "samsung-4.mp4"), ("loop", "samsung-5.mp4"), "2"],
    },
    {
        "slug": "conde-nast-sia",
        "title": "Condé Nast Social Influencer Awards",
        "zh": "第一屆 康泰納仕 社群風格名人獎｜主視覺與活動官網",
        "client": "Condé Nast Taiwan",
        "cat": "product",
        "role": ["Design Director｜Jeter Chou", "Key Visual & Website Design｜Harvey Huang"],
        "tags": ["Key Visual", "Campaign Website", "Logo", "RWD"],
        "featured": True,
        "lead": "為第一屆康泰納仕社群風格名人獎打造主視覺、Logo 與活動官網，從品牌特色與活動概念出發，將視覺創意轉化為符合 RWD 規範的數位體驗。",
        "sections": [],
        "gallery": ["2", "3", "4", "5", ("youtube", "VD0tOjoo1-8", "2019 SIA 康泰納仕社群風格名人頒獎典禮")],
        "links": [("活動官網", "https://www.vogue.com.tw/sia/")],
    },
    {
        "slug": "conde-nast-summit",
        "title": "Social Influencer Summit 2020",
        "zh": "2020 康泰納仕 社群風格名人趨勢高峰會｜主視覺設計",
        "client": "Condé Nast Taiwan",
        "cat": "product",
        "role": ["Design Director｜Jeter Chou", "Key Visual Design｜Harvey Huang"],
        "tags": ["Key Visual", "Campaign Website", "Social Media"],
        "lead": "「直擊 Z 世代」— 2020 社群風格名人趨勢高峰會的主視覺，延展至活動官網、社群與宣傳素材。",
        "sections": [],
        "layout": "tall",
        "gallery": ["1"],
    },
    {
        "slug": "gq-business-school",
        "title": "GQ Business School",
        "zh": "GQ 風格商業學校｜系列主視覺設計",
        "client": "Condé Nast Taiwan · GQ",
        "cat": "product",
        "role": ["Design Director｜Jeter Chou", "Key Visual Design｜Harvey Huang"],
        "tags": ["Key Visual", "Campaign Website", "Print"],
        "lead": "GQ Business School 風格商業學校系列講座主視覺，包含創二代接班、藝術如何點石成金、購物的未來、話題餐廳的誕生等主題，延展至網站、社群與印刷品。",
        "sections": [],
        "layout": "tall",
        "gallery": ["1"],
    },
    {
        "slug": "vogue-illustration",
        "title": "VOGUE Taiwan Illustration",
        "zh": "VOGUE Taiwan 雙語讀時尚｜插畫設計",
        "client": "Condé Nast Taiwan · VOGUE",
        "cat": "visual",
        "role": ["Illustration｜Harvey Huang"],
        "tags": ["Illustration", "Social Media", "Editorial"],
        "lead": "「用英文，打開更大的自己。」為 VOGUE Taiwan 雙語讀時尚系列繪製插畫，從自我介紹、升遷加薪、旅行到餐廳點餐，以時尚女性的生活場景延伸出一系列社群內容。",
        "sections": [],
        "layout": "grid3",
        "gallery": ["1", "2", "3", "4", "5"],
    },
    {
        "slug": "asahi-airline",
        "title": "Asahi Airline",
        "zh": "Asahi 辛口航空｜VI 提案",
        "client": "Asahi（Proposal）",
        "cat": "visual",
        "role": ["Visual Identity Design｜Harvey Huang"],
        "tags": ["Visual Identity", "Logo", "Print"],
        "lead": "More than a destination — 以「辛口航空」為概念的品牌活動識別提案，包含 Logo、邀請機票券、紙袋與入場手環等延伸應用。",
        "sections": [],
        "gallery": ["1", "2", "3", "4"],
    },
]

ORDER_FEATURED = ["volkswagen-app", "taipei-twins", "diageo-line-mini-app", "shin-kong-mitsukoshi", "singleton-website", "conde-nast-sia"]
